### ISSUE TITLE
Add constructor overload for type CloudStorageAccount on AzureStorageAttachmentConfiguration

### ISSUE THREAD

**Issue by bryanvam** [SeanFeldman/ServiceBus.AttachmentPlugin#195]

**Comment by SeanFeldman** [comment]
@bryanvam could you please provide details on the use case and why the current API is not enough? I’d like to understand what specifically this change would help with. Thank you.

**Comment by bryanvam** [comment]
CloudStorageAccount.Parse(connectionString) returns CloudStorageAccount and is used to create a client. I often register this as a singleton instance so it is convinient to new up a client in different places. Injecting a connectionstring or passing it around in a IOptions adds extra complexity.

Example of one of my services taking in CloudStorageAccount

```c#
public class AzureDocumentService : StorageBase, IDocumentService
{
  public AzureDocumentService(CloudStorageAccount storageAccount, IHostingEnvironment env)
            : base(storageAccount, env)
  {
  }
  //...
}
```

**Comment by SeanFeldman** [comment]
The plugin does not use Blob clients. That's why it does not require `CloudStorageAccount`. But I can see two options for you moving forward where you do not have to provide a connection string. 

**Option 1**

`AzureStorageAttachmentConfiguration` has an overload that accepts `StorageCredentials`. And `StorageCredentials` can be retrieved from a `CloudStorageAccount.Credentials`. It can also be used to retrieve `BlobEndpoint` so that you don't have to pass around a string for that value. This way you can still use `CloudStorageAccount`. Does that address your 

**Option 2**

Implement and inject a singleton of `IProvideStorageConnectionString` that takes the dependency on your `CloudStorageAccount` and use `AzureStorageAttachmentConfiguration` overload accepting it.

Let me know if this work for you you.

**Comment by SeanFeldman** [comment]
@bryanvam, have you had a chance to review the options?
If you think that doesn't help, please let me know. Thanks.

**Comment by SeanFeldman** [comment]
@bryanvam I'm going to close the issue as there was no follow-up. If the suggested options don't work, please let me know.
