### ISSUE TITLE
Integration with Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [SeanFeldman/ServiceBus.AttachmentPlugin#30]
Are there plans to integrate with Azure Key Vault?

The plugin would authenticate with a specific AD application, fetch the storage key from a configured vault & secret and use that.

## Pros
- Allows consumers to automatically roll storage account keys without the plugin noticing it
- Have audit logs of whom is using the keys
- Re-use existing secret management approaches

## Cons
- Additional dependency on Key Vault (and thus AD)
- Additional network roundtrip

## Update

An approch described [here](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/issues/30#issuecomment-371665749) will be implemented. It will allow integration with Azure Key Vault w/o the dependency on KeyVault.

**Comment by SeanFeldman** [comment]
I like the idea. The dependency on Key Vault is less ideal, but could be managed through having an additional package to extend ServiceBus.AttachmentPlugin.
Have no good hands on experience with Key Vault. If you could point me to a quick start/good resource, I'll have a look and get it going.

**Comment by jtaubensee** [comment]
Hey @SeanFeldman - I like the idea as well. I think one decision, or possible setting to include, is whether or not to do the encryption inside the process, or in KeyVault. KeyVault has two different kinds of values: secrets and keys. Keys can be generated by KeyVault, and never pulled out. You can then have KeyVault perform all of the cryptographic operations necessary, so the library will never even see the key. Secrets are really just text that can be retrieved in order to perform encryption operations locally. Here is more information on the differences: https://docs.microsoft.com/rest/api/keyvault/about-keys--secrets-and-certificates

Here is more information on how to authenticate with KeyVault. https://docs.microsoft.com/azure/key-vault/service-to-service-authentication

Here is the KeyVault Service Bus plugin. I'm still not sure why it was removed, but I am guessing it is because we decided to do the encryption locally, and we used AES encryption instead of SHA? Either way, I still think that the flow with KeyVault is appropriate.

https://github.com/Azure/azure-service-bus-dotnet-plugins/pull/1/files

**Comment by tomkerkhove** [comment]
@jtaubensee There is also an issue for the plugin btw (https://github.com/Azure/azure-service-bus-dotnet-plugins/issues/17)

On the topic - For this plugin I think the way to go is Key Vault Secret as we are only interested in the Key or SAS for a specific storage account/container.

If you elaborate on how you'd want to do this I can help you a bit or jump in.

**Comment by jtaubensee** [comment]
@tomkerkhove - Apologies, I missed the point of this. I would agree with using a secret for the connection string.

**Comment by tomkerkhove** [comment]
@jtaubensee Don't worry, thanks for elaborating anyway!

**Comment by SeanFeldman** [comment]
**Update** after thinking about this a bit more, I've decided to add ability to register providers for connection strings and create a separate nuget package with KeyVault provider. Reason for separation is not to force coupling with [KeyVault package](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/) which has some dependencies. By doing so, a change in keyvault provider would not require a change of this package.

**Comment by tomkerkhove** [comment]
Makes perfect sense!

**Comment by SeanFeldman** [comment]
Pre-released package of KeyVault provider is available on nuget https://www.nuget.org/packages/ServiceBus.AttachmentPlugin.KeyVaultProvider/

**Comment by SeanFeldman** [comment]
@tomkerkhove @jtaubensee help to spread the word and make this world a safer place 😃
