### ISSUE TITLE
Storage cleanup

### ISSUE THREAD

**Issue by Blackbaud-JoshuaWinter** [SeanFeldman/ServiceBus.AttachmentPlugin#6]
Hello, does this plugin somehow cleanup old messages from the storage account? Glancing at the source code it seems to not take care of any cleanup. Would you recommend a cleanup strategy?

Thanks.

**Comment by SeanFeldman** [comment]
@Blackbaud-JoshuaWinter cleanup strategies vary between different project. For a message representing an event, cleanup is a bit tricky. What cleanup strategy are you looking for specifically?

**Comment by SeanFeldman** [comment]
The current behavior does something to help with cleanup. It stamps blobs for messages with TTL set with a custom attributed `_ValidUntilUtc`. If you use TTL with your messages, you could periodically scan blobs and remove if custom attribute is set to a date that is in past.

**Comment by SeanFeldman** [comment]
@Blackbaud-JoshuaWinter I'm going to close this issue since there was not a lot of feedback. I suspect is has to do with the reasons outlined here: https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/issues/6#issuecomment-323274934.

In case you'd like to send a PR or have some ideas how to help your scenario, please chime in 🙂
